### ISSUE TITLE
Heading value is always zero

### ISSUE THREAD

**Issue by thanksforthefreeaccount** [thrnz/earthvr-custom-tours#3]
Hi, great tool. In my case, the heading values in the textpb file are always zero which means it is always showing the wrong direction. Is there a way to fix this?
If I can get the metadata behind my GEVR screenshots, maybe I can fill it manually in the textpb. Do you know how I can do this? I am a newbee.

**Comment by thrnz** [comment]
This tool doesn't pull a heading value from the metadata and will always set it to 0.

I can't recall if the heading is remembered when you re-visit a saved place in the app itself. If it is, then chances are it'll be in the metadata somewhere and might be able to be extracted. It's been a while since I last poked around but if I get some time I might reacquaint myself and see if its possible. Otherwise, it would have to be manually entered using a text editor.

If you're interested in poking around, the metadata itself is stored using [Protocol Buffers](https://developers.google.com/protocol-buffers). I should probably update this repo a bit as its somewhat behind whats on AppEngine.

**Comment by thanksforthefreeaccount** [comment]
Thanks. Yes, when you save a place, it remembers the heading and always respawns from that angle. If I look inside the tours created by GEVR, I see that the heading value is non-zero.

My workaround at the moment is to change the heading until I find the right angle. But this takes quite a long time since I have to restart GEVR each time to see the changes.

I will poke around with protocol buffers and see if I can figure it out. I would also be interested in finding out if I can add pins to places.

**Comment by thrnz** [comment]
These are my old notes of whats stored in the saved jpg metadata:
```
protoc.exe --decode_raw < chchcentral.txt
1 {
  1: "Christchurch Central"
  1: "Christchurch, New Zealand"
  2: "Imagery \302\2512016 Google, CNES / Astrium, Data LDEO-Columbia, NSF, NOAA, Data SIO, NOAA, U.S. Navy, NGA, GEBCO, DigitalGlobe, Landsat, TerraMetrics, U.S. Geological Survey"
  3: 570
  4: 0
  5: 983
  6: 1106
}
2 {
  1 {
    1: "Christchurch Central"
    2: "Christchurch, New Zealand"
    3 {
      1 {
        1: 0xc045c4567b6b419a << lat (double -43.53388922440645)
        2: 0x406593c1d52f46e6 << long (double 172.61741122468737)
        3: 0xc1584db080000000 << is always this(?)
      }
      2 {
        1: 0xbf383925fb874200
        2: 0xc0e83713f1e82cf1
        3: 0xbfb383d3cc3c1694
      }
      3: 0x405675eba4b593e2
      4: 3
      5: 0x40600ef20ac07f56 << scale (double 128.46704614255094)
      6: 0
    }
    4 {
      1: 2015
      2: 8
      3: 26
      4: 0
      5: 6
      6: 26
    }
  }
}
```
I never did figure out what a lot of it was. Just enough to get the tour generator to function.

**Comment by thrnz** [comment]
`3: 0x405675eba4b593e2`
I wonder if that's it. I just went through a bunch of saved places and this was always between `-360` and `360`. The heading value in the built-in tours seems to also be somewhere within this range.

I've put up a test build at https://20220623t201203-dot-earthvr-custom-tours.uc.r.appspot.com that uses that value for `heading` for generated tours. Let me know if it's potentially on the right track. I don't have the Vive set up at the moment to easily test it.

**Comment by thanksforthefreeaccount** [comment]
That's it mate. You've fixed it. You just saved me a lot of time. Cheers!
